version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db_typeorm_windows
    ports:
      - '5433:5432'
      # 1) куда будет развернуто внутри докера! в постгресе тоже! - внешний
      # 2) порт, по которому будет отзываться! - внутренний
    environment:
      POSTGRES_DB: social_network_typeorm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 230900