version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db_typeorm_windows
    ports:
      - '5433:5432'
      # 1) куда будет развернуто внутри докера! в постгресе тоже!
      # 2) порт, по которому будет отзываться!
    environment:
      POSTGRES_DB: social_network_develope
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 230900
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: