name: Tests and Vercel Deploy

on:
  push:
    branches: ['master']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production # Указываем, что используем продакшн среду

    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Login to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Используем токен из секретов
        run: echo $VERCEL_TOKEN | vercel login --token

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production
      - name: Build Project Artifacts
        run: vercel build --prod
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod
