name: Tests and Vercel Deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# Указывает, что workflow будет запускаться при каждом push в ветку master.
on:
  push: # действие и ветка в гитхаб для запуска воркфлоу
    branches: ['master']

# Важно указать очередность джоб! Чтоб тесты были первее деплоя!
jobs:
  tests:
    name: Tests # название работы в нашем pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # клонируем репозиторий

      - name: Install dependencies
        run: yarn # устанавливаем зависимости

      - name: Run e2e tests
        run: yarn test:e2e # запускаем скрипт e2e тестов
        env:
          ENV: ${{ vars.ENV_GH }} # указываем необходимые переменные для тестов

  deploy: # Убедитесь, что отступы здесь такие же, как и в 'tests'
    name: Deploy # название работы в нашем pipeline
    needs: tests # Указывает, что это задание зависит от завершения задания tests.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
